# Build stage
FROM node:latest AS build
RUN apt update && apt install -y git
# Set working directory in the container
WORKDIR /app
# Copy package.json and package-lock.json
COPY package.json .
COPY package-lock.json .
# Install dependencies
RUN npm install
# Copy the rest of the application files
COPY . .
# Build the application
RUN npm run build --only=production
# Set environment variables
ARG PORT_ARG=4000
ENV PORT=${PORT_ARG}
EXPOSE $PORT_ARG

# Specify the command to run your application
CMD ["npm", "start"]




### using nginx     
## Build stage
# FROM node:latest AS build
# # Set working directory in the container
# WORKDIR /www
# # Copy package.json and package-lock.json
# COPY package*.json .
# # Install dependencies
# RUN npm install
# # Copy the rest of the application files
# COPY . .
# # Build the application
# RUN npm run build
# # Production stage
# FROM nginx:alpine AS production
# WORKDIR /app
# # Copy built artifacts from the build stage
# COPY --from=build /www/dist /app
# # Copy nginx configuration file
# COPY nginx.conf /etc/nginx/nginx.conf 
# # Expose port 80
# EXPOSE 80
# # Start nginx
# CMD ["nginx", "-g", "daemon off;"]